repos:
  - repo: https://github.com/terraform-docs/terraform-docs
    rev: "v0.16.0"
    hooks:
      - id: terraform-docs-go
        args: ["markdown","--hide-empty=true","-c", ".terraform.docs.yml", "./modules"]
